@ticketedEventId = f02fd7d4-7c12-a18a-a31d-e9448d62c433
@ticketTypeId = 705e564e-be64-77a2-b552-2fcb19506385

POST http://localhost:5100/teams
Content-Type: application/json

{
  "name": "Azure Fest"
}

###

@teamId = e8ad4949-1d2a-ae04-c763-336dea584a5f

POST http://localhost:5100/teams/{{teamId}}/members
Content-Type: application/json

{
  "email": "a.molenkamp@gmail.com",
  "role": "GlobalAdmin"
}

###

@codeVerifier = foo
@codeChallenge = LCa0a2j_xo_5m0U8HTBBNBNCLXBkg7-g-YpeiGJm564

POST http://localhost:5100/authorize
Content-Type: application/json

{
  "email": "a.molenkamp@gmail.com",
  "codeChallenge": "{{codeChallenge}}"
}

###

@authorizationCode = ???

POST http://localhost:5100/token
Content-Type: application/json

{
  "code": "{{authorizationCode}}",
  "codeVerifier": "{{codeVerifier}}"
}

###

POST http://localhost:5100/events
Content-Type: application/json

{
  "name": "Bitbash",
  "startDay": "2026-01-24",
  "endDay": "2026-01-25",
  "salesStartDateTime": "2025-09-01T00:00:00Z",
  "salesEndDateTime": "2026-01-23T00:00:00Z",
  "ticketTypes": [
    {
      "name": "Conference",
      "startDateTime": "2026-01-25T09:00:00Z",
      "endDateTime": "2026-01-25T16:00:00Z",
      "maxCapacity": 200
    }
  ]
}

###

GET http://localhost:5100/events/{{ticketedEventId}}

###

POST http://localhost:5100/registrations
Content-Type: application/json

{
  "email": "a.molenkamp@gmail.com",
  "firstName": "Sander",
  "lastName": "Molenkamp",
  "organizationName": "Info Support",
  "ticketedEventId": "{{ticketedEventId}}",
  "ticketTypes": [
    "{{ticketTypeId}}"
  ]
}
