@ticketedEventId = f02fd7d4-7c12-a18a-a31d-e9448d62c433
@ticketTypeId = 705e564e-be64-77a2-b552-2fcb19506385

###

POST http://localhost:5100/events
Content-Type: application/json

{
  "name": "Bitbash",
  "startDay": "2026-01-24",
  "endDay": "2026-01-25",
  "salesStartDateTime": "2025-09-01T00:00:00Z",
  "salesEndDateTime": "2026-01-23T00:00:00Z",
  "ticketTypes": [
    {
      "name": "Conference",
      "startDateTime": "2026-01-25T09:00:00Z",
      "endDateTime": "2026-01-25T16:00:00Z",
      "maxCapacity": 200
    }
  ]
}

###

GET http://localhost:5100/events/{{ticketedEventId}}

###

POST http://localhost:5100/registrations
Content-Type: application/json

{
  "email": "a.molenkamp@gmail.com",
  "firstName": "Sander",
  "lastName": "Molenkamp",
  "organizationName": "Info Support",
  "ticketedEventId": "{{ticketedEventId}}",
  "ticketTypes": [
    "{{ticketTypeId}}"
  ]
}
