### Get Keycloak token

POST http://localhost:8080/realms/admitto/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=admitto-test-runner&username=alice&password=alice

> {% client.global.set("accessToken", response.body.access_token); %}

### Create a new team

POST http://localhost:5100/teams/v1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Acme",
  "emailSettings": {
    "senderEmail": "no-reply@example.com",
    "smtpServer": "smtp.example.com",
    "smtpPort": 587
  },
  "members": [
    { "email": "bob@example.com", "role": "manager" }
  ]
}

###

@teamId = d86c0337-74f9-336d-5038-eca92f8a73ae

### Create a new event

POST http://localhost:5100/events/v1
Content-Type: application/json

{
  "teamId": "{{teamId}}",
  "name": "AwesomeCon",
  "startTime": "2050-01-24T09:00:00Z",
  "endTime": "2050-01-25T16:00:00Z",
  "registrationStartTime": "2049-09-01T00:00:00Z",
  "registrationEndTime": "2050-01-23T18:00:00Z",
  "ticketTypes": [
    {
      "name": "General Admission",
      "slotName": "Default",
      "maxCapacity": 100
    }
  ]
}

###

@ticketedEventId = d61cc879-739a-3e1b-b4fd-129089d2a842
@ticketTypeId = 0f7c8929-6d71-3e6d-4d60-307f6d3349ab

### Create a new registration

POST http://localhost:5100/registrations/v1
Content-Type: application/json

{
  "ticketedEventId": "{{ticketedEventId}}",
  "email": "test@example.com",
  "firstName": "John",
  "lastName": "Doe",
  "details": {
    "organizationName": "Example Corp"
  },
  "tickets": {
    "{{ticketTypeId}}": 1
  }
}

###

@registrationId = e55e9d1a-34f5-b017-5099-d5c3f047518e

###

