// <auto-generated />
using System;
using System.Text.Json;
using Amolenk.Admitto.Core.Email.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amolenk.Admitto.Core.Email.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EmailDbContext))]
    [Migration("20260629190453_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("email")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amolenk.Admitto.Core.Email.Application.Projections.EventEmailContext.EventEmailContextView", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("TicketedEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticketed_event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EventName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_name");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("PublicSlug")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("public_slug");

                    b.Property<int?>("ReconfirmCadenceHours")
                        .HasColumnType("integer")
                        .HasColumnName("reconfirm_cadence_hours");

                    b.Property<DateTimeOffset?>("ReconfirmClosesAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reconfirm_closes_at");

                    b.Property<int?>("ReconfirmMinEmailIntervalHours")
                        .HasColumnType("integer")
                        .HasColumnName("reconfirm_min_email_interval_hours");

                    b.Property<DateTimeOffset?>("ReconfirmOpensAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reconfirm_opens_at");

                    b.Property<int?>("SelfServiceTicketTypeCount")
                        .HasColumnType("integer")
                        .HasColumnName("self_service_ticket_type_count");

                    b.Property<long>("TicketCatalogVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_catalog_version");

                    b.Property<long>("TicketedEventVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("ticketed_event_version");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("TeamId", "TicketedEventId");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_event_email_context_view_team_id");

                    b.HasIndex("IsArchived", "ReconfirmOpensAt", "ReconfirmClosesAt")
                        .HasDatabaseName("IX_event_email_context_view_reconfirm_schedule");

                    b.ToTable("event_email_context_view", "email");
                });

            modelBuilder.Entity("Amolenk.Admitto.Core.Email.Application.Projections.TeamEmailContext.TeamEmailContextView", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("AccentColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("accent_color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("ReplyToEmailAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("reply_to_email_address");

                    b.Property<string>("TeamName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("team_name");

                    b.Property<long>("TeamVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("team_version");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("TeamId");

                    b.ToTable("team_email_context_view", "email");
                });

            modelBuilder.Entity("Amolenk.Admitto.Core.Email.Domain.Entities.BulkEmailJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancellationRequestedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancellation_requested_at");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<int>("CancelledCount")
                        .HasColumnType("integer")
                        .HasColumnName("cancelled_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email_type");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<bool>("IsSystemTriggered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_triggered");

                    b.Property<DateTimeOffset>("LastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed_at");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("last_changed_by");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_count");

                    b.Property<int>("SentCount")
                        .HasColumnType("integer")
                        .HasColumnName("sent_count");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("TextBody")
                        .HasColumnType("text")
                        .HasColumnName("text_body");

                    b.Property<Guid>("TicketedEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticketed_event_id");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("triggered_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_bulk_email_jobs_status");

                    b.HasIndex("TicketedEventId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_bulk_email_jobs_event_created_at");

                    b.ToTable("bulk_email_jobs", "email");
                });

            modelBuilder.Entity("Amolenk.Admitto.Core.Email.Domain.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BulkEmailJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("bulk_email_job_id");

                    b.Property<int>("DeliveryAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_attempt_count");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email_type");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient");

                    b.Property<Guid?>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("StatusUpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("status_updated_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid?>("TicketedEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticketed_event_id");

                    b.HasKey("Id");

                    b.HasIndex("BulkEmailJobId");

                    b.HasIndex("Recipient", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_email_log_system_recipient_idempotency")
                        .HasFilter("ticketed_event_id IS NULL");

                    b.HasIndex("TicketedEventId", "RegistrationId")
                        .HasDatabaseName("IX_email_log_event_registration");

                    b.HasIndex("TicketedEventId", "SentAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_email_log_event_sent_at");

                    b.HasIndex("TicketedEventId", "Recipient", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_email_log_event_recipient_idempotency")
                        .HasFilter("ticketed_event_id IS NOT NULL");

                    b.ToTable("email_log", "email");
                });

            modelBuilder.Entity("Amolenk.Admitto.Core.Shared.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_outbox_state")
                        .HasFilter("state = 'Pending'");

                    b.HasIndex("State", "CreatedAt")
                        .HasDatabaseName("IX_outbox_pending_created_at")
                        .HasFilter("state = 'Pending'");

                    b.ToTable("outbox", "email");
                });

            modelBuilder.Entity("Amolenk.Admitto.Core.Email.Domain.Entities.BulkEmailJob", b =>
                {
                    b.OwnsMany("Amolenk.Admitto.Core.Email.Domain.ValueObjects.BulkEmailRecipient", "Recipients", b1 =>
                        {
                            b1.Property<Guid>("BulkEmailJobId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("DisplayName")
                                .HasJsonPropertyName("display_name");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasJsonPropertyName("email");

                            b1.Property<string>("LastError")
                                .HasJsonPropertyName("last_error");

                            b1.Property<string>("ParametersJson")
                                .IsRequired()
                                .HasJsonPropertyName("parameters");

                            b1.Property<Guid?>("RegistrationId")
                                .HasJsonPropertyName("registration_id");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasJsonPropertyName("status");

                            b1.HasKey("BulkEmailJobId", "__synthesizedOrdinal");

                            b1.ToTable("bulk_email_jobs", "email");

                            b1
                                .ToJson("recipients")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BulkEmailJobId");
                        });

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("Amolenk.Admitto.Core.Email.Domain.Entities.EmailLog", b =>
                {
                    b.HasOne("Amolenk.Admitto.Core.Email.Domain.Entities.BulkEmailJob", null)
                        .WithMany()
                        .HasForeignKey("BulkEmailJobId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
