// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Amolenk.Admitto.Core.Email.Infrastructure.Persistence.Migrations;

[DbContext(typeof(EmailDbContext))]
[Migration("20260829000002_AddReconfirmationBatch")]
partial class AddReconfirmationBatch
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // The canonical target model is maintained in EmailDbContextModelSnapshot.
        // This migration's operations are intentionally explicit so it can be
        // applied without depending on design-time service registration.
    }
}
