// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Amolenk.Admitto.Core.Email.Infrastructure.Persistence.Migrations;

[DbContext(typeof(EmailDbContext))]
[Migration("20260831000001_RemoveReconfirmationBatch")]
partial class RemoveReconfirmationBatch
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // The canonical target model is maintained in EmailDbContextModelSnapshot.
    }
}
