// <auto-generated />
using System;
using System.Text.Json;
using Amolenk.Admitto.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amolenk.Admitto.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250624070630_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amolenk.Admitto.Application.ReadModel.Views.AttendeeActivityView", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("activity");

                    b.Property<Guid>("AttendeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendee_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("attendee_activities", (string)null);
                });

            modelBuilder.Entity("Amolenk.Admitto.Domain.Entities.AttendeeRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TicketedEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.HasKey("Id");

                    b.ToTable("attendee_registrations", (string)null);
                });

            modelBuilder.Entity("Amolenk.Admitto.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Amolenk.Admitto.Domain.Entities.TicketedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("RegistrationEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_end_time");

                    b.Property<DateTimeOffset>("RegistrationStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_start_time");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("ticketed_events", (string)null);
                });

            modelBuilder.Entity("Amolenk.Admitto.Domain.ValueObjects.EmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sent");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recipient_email");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.ToTable("email_messages", (string)null);
                });

            modelBuilder.Entity("Amolenk.Admitto.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<bool>("Priority")
                        .HasColumnType("boolean")
                        .HasColumnName("priority");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Amolenk.Admitto.Domain.Entities.AttendeeRegistration", b =>
                {
                    b.OwnsMany("Amolenk.Admitto.Domain.ValueObjects.AttendeeDetail", "Details", b1 =>
                        {
                            b1.Property<Guid>("AttendeeRegistrationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AttendeeRegistrationId", "__synthesizedOrdinal");

                            b1.ToTable("attendee_registrations");

                            b1.ToJson("details");

                            b1.WithOwner()
                                .HasForeignKey("AttendeeRegistrationId");
                        });

                    b.OwnsMany("Amolenk.Admitto.Domain.ValueObjects.TicketQuantity", "Tickets", b1 =>
                        {
                            b1.Property<Guid>("AttendeeRegistrationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.Property<Guid>("TicketTypeId")
                                .HasColumnType("uuid");

                            b1.HasKey("AttendeeRegistrationId", "__synthesizedOrdinal");

                            b1.ToTable("attendee_registrations");

                            b1.ToJson("tickets");

                            b1.WithOwner()
                                .HasForeignKey("AttendeeRegistrationId");
                        });

                    b.Navigation("Details");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Amolenk.Admitto.Domain.Entities.Team", b =>
                {
                    b.OwnsMany("Amolenk.Admitto.Domain.Entities.TeamMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TeamId", "__synthesizedOrdinal");

                            b1.ToTable("teams");

                            b1.ToJson("members");

                            b1.WithOwner()
                                .HasForeignKey("TeamId");
                        });

                    b.OwnsOne("Amolenk.Admitto.Domain.ValueObjects.EmailSettings", "EmailSettings", b1 =>
                        {
                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SenderEmail")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("SmtpPort")
                                .HasColumnType("integer");

                            b1.Property<string>("SmtpServer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TeamId");

                            b1.ToTable("teams");

                            b1.ToJson("email_settings");

                            b1.WithOwner()
                                .HasForeignKey("TeamId");
                        });

                    b.Navigation("EmailSettings")
                        .IsRequired();

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Amolenk.Admitto.Domain.Entities.TicketedEvent", b =>
                {
                    b.HasOne("Amolenk.Admitto.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Amolenk.Admitto.Domain.Entities.TicketType", "TicketTypes", b1 =>
                        {
                            b1.Property<Guid>("TicketedEventId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxCapacity")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("RemainingCapacity")
                                .HasColumnType("integer");

                            b1.Property<string>("SlotName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TicketedEventId", "__synthesizedOrdinal");

                            b1.ToTable("ticketed_events");

                            b1.ToJson("ticket_types");

                            b1.WithOwner()
                                .HasForeignKey("TicketedEventId");
                        });

                    b.OwnsMany("Amolenk.Admitto.Domain.ValueObjects.EmailTemplate", "EmailTemplates", b1 =>
                        {
                            b1.Property<Guid>("TicketedEventId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TicketedEventId", "__synthesizedOrdinal");

                            b1.ToTable("ticketed_events");

                            b1.ToJson("email_templates");

                            b1.WithOwner()
                                .HasForeignKey("TicketedEventId");
                        });

                    b.Navigation("EmailTemplates");

                    b.Navigation("TicketTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
