// <auto-generated />
using System;
using System.Text.Json;
using Amolenk.Admitto.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amolenk.Admitto.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amolenk.Admitto.Application.ReadModel.Views.AttendeeActivityView", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("activity");

                    b.Property<Guid>("AttendeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendee_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("attendee_activities", (string)null);
                });

            modelBuilder.Entity("Amolenk.Admitto.Application.UseCases.Email.EmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttendeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendee_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recipient_email");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TicketedEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticketed_event_id");

                    b.HasKey("Id");

                    b.ToTable("email_messages", (string)null);
                });

            modelBuilder.Entity("Amolenk.Admitto.Domain.Entities.AttendeeRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("last_name");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("organization_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("TicketedEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.HasKey("Id");

                    b.ToTable("attendee_registrations", (string)null);
                });

            modelBuilder.Entity("Amolenk.Admitto.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Amolenk.Admitto.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<bool>("Priority")
                        .HasColumnType("boolean")
                        .HasColumnName("priority");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Amolenk.Admitto.Domain.Entities.AttendeeRegistration", b =>
                {
                    b.OwnsOne("Amolenk.Admitto.Domain.ValueObjects.TicketOrder", "TicketOrder", b1 =>
                        {
                            b1.Property<Guid>("AttendeeRegistrationId")
                                .HasColumnType("uuid");

                            b1.HasKey("AttendeeRegistrationId");

                            b1.ToTable("attendee_registrations");

                            b1.ToJson("ticket_order");

                            b1.WithOwner()
                                .HasForeignKey("AttendeeRegistrationId");
                        });

                    b.Navigation("TicketOrder")
                        .IsRequired();
                });

            modelBuilder.Entity("Amolenk.Admitto.Domain.Entities.Team", b =>
                {
                    b.OwnsMany("Amolenk.Admitto.Domain.Entities.TeamMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("role");

                            b1.HasKey("TeamId", "__synthesizedOrdinal");

                            b1.ToTable("teams");

                            b1.ToJson("members");

                            b1.WithOwner()
                                .HasForeignKey("TeamId");
                        });

                    b.OwnsMany("Amolenk.Admitto.Domain.Entities.TicketedEvent", "ActiveEvents", b1 =>
                        {
                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset>("EndDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("RegistrationEndDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("RegistrationStartDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("StartDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("TeamId", "__synthesizedOrdinal");

                            b1.ToTable("teams");

                            b1.ToJson("active_events");

                            b1.WithOwner()
                                .HasForeignKey("TeamId");

                            b1.OwnsMany("Amolenk.Admitto.Domain.Entities.TicketType", "TicketTypes", b2 =>
                                {
                                    b2.Property<Guid>("TicketedEventTeamId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("TicketedEvent__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("MaxCapacity")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int>("RemainingCapacity")
                                        .HasColumnType("integer");

                                    b2.Property<string>("SlotName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("TicketedEventTeamId", "TicketedEvent__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("teams");

                                    b2.WithOwner()
                                        .HasForeignKey("TicketedEventTeamId", "TicketedEvent__synthesizedOrdinal");
                                });

                            b1.Navigation("TicketTypes");
                        });

                    b.Navigation("ActiveEvents");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
