// <auto-generated/>
#pragma warning disable CS0618
using Amolenk.Admitto.Cli.Api.Teams.Item.Email.Templates;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Amolenk.Admitto.Cli.Api.Teams.Item.Email
{
    /// <summary>
    /// Builds and executes requests for operations under \teams\{teamSlug}\email
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EmailRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The templates property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Email.Templates.TemplatesRequestBuilder Templates
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Email.Templates.TemplatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Teams.Item.Email.EmailRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmailRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/teams/{teamSlug}/email", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Teams.Item.Email.EmailRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmailRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/teams/{teamSlug}/email", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
