// <auto-generated />
using System;
using Amolenk.Admitto.Core.Badges.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amolenk.Admitto.Core.Badges.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BadgesDbContext))]
    [Migration("20260630142505_StoreEnumsAsText")]
    partial class StoreEnumsAsText
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("badges")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amolenk.Admitto.Core.Badges.Domain.Entities.BadgeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed_at");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("last_changed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("badges_events", "badges");
                });

            modelBuilder.Entity("Amolenk.Admitto.Core.Badges.Domain.Entities.BadgeInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BadgeTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_type_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("LastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed_at");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("last_changed_by");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BadgeTypeId")
                        .HasDatabaseName("IX_badge_instances_badge_type_id");

                    b.HasIndex("TeamId", "EventId", "BadgeTypeId")
                        .HasDatabaseName("IX_badge_instances_team_id_event_id_badge_type_id");

                    b.ToTable("badge_instances", "badges");
                });

            modelBuilder.Entity("Amolenk.Admitto.Core.Badges.Domain.Entities.BadgeEvent", b =>
                {
                    b.OwnsMany("Amolenk.Admitto.Core.Badges.Domain.Entities.BadgeType", "BadgeTypes", b1 =>
                        {
                            b1.Property<Guid>("BadgeEventId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("Id")
                                .HasJsonPropertyName("id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasJsonPropertyName("kind");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasJsonPropertyName("name");

                            b1.PrimitiveCollection<string>("TicketTypeIds")
                                .IsRequired()
                                .HasJsonPropertyName("ticket_type_ids");

                            b1.HasKey("BadgeEventId", "__synthesizedOrdinal");

                            b1.ToTable("badges_events", "badges");

                            b1
                                .ToJson("badge_types")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BadgeEventId");
                        });

                    b.Navigation("BadgeTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
