parent=keycloak.v2
import=common/keycloak

styles=css/login.css
locales=en

kcLogoLink=https://admitto.local
kcHeaderWrapperClass=admitto-header
kcFormCardClass=admitto-card
kcButtonPrimaryClass=pf-v5-c-button pf-m-primary admitto-button-primary
