// <auto-generated />
using System;
using System.Text.Json;
using Amolenk.Admitto.Module.Registrations.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amolenk.Admitto.Module.Registrations.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RegistrationsDbContext))]
    partial class RegistrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("registrations")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amolenk.Admitto.Module.Registrations.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActivityType")
                        .HasColumnType("integer")
                        .HasColumnName("activity_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId", "ActivityType", "OccurredAt")
                        .HasDatabaseName("IX_activity_log_registration_type_occurred");

                    b.ToTable("activity_log", "registrations");
                });

            modelBuilder.Entity("Amolenk.Admitto.Module.Registrations.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("AllowedTicketTypeSlugs")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_ticket_type_slugs");

                    b.Property<bool>("BypassRegistrationWindow")
                        .HasColumnType("boolean")
                        .HasColumnName("bypass_registration_window");

                    b.Property<Guid>("Code")
                        .HasColumnType("uuid")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed_at");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("last_changed_by");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EventId");

                    b.ToTable("coupons", "registrations");
                });

            modelBuilder.Entity("Amolenk.Admitto.Module.Registrations.Domain.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("email_hash");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EmailHash", "EventId");

                    b.ToTable("otp_codes", "registrations");
                });

            modelBuilder.Entity("Amolenk.Admitto.Module.Registrations.Domain.Entities.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalDetails")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_details")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("HasReconfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("has_reconfirmed");

                    b.Property<DateTimeOffset>("LastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed_at");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("last_changed_by");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset?>("ReconfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reconfirmed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_registrations_event_id_email");

                    b.ToTable("registrations", "registrations");
                });

            modelBuilder.Entity("Amolenk.Admitto.Module.Registrations.Domain.Entities.TicketCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EventStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("event_status");

                    b.Property<DateTimeOffset>("LastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed_at");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("last_changed_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("ticket_catalog", "registrations");
                });

            modelBuilder.Entity("Amolenk.Admitto.Module.Registrations.Domain.Entities.TicketedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalDetailSchema")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_detail_schema")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<DateTimeOffset>("LastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed_at");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("last_changed_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("SigningKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signing_key");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("team_slug");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("UTC")
                        .HasColumnName("time_zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("website_url");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "Slug")
                        .IsUnique();

                    b.ToTable("ticketed_events", "registrations");
                });

            modelBuilder.Entity("Amolenk.Admitto.Module.Shared.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("outbox", "registrations");
                });

            modelBuilder.Entity("Amolenk.Admitto.Module.Registrations.Domain.Entities.Registration", b =>
                {
                    b.OwnsMany("Amolenk.Admitto.Module.Registrations.Domain.ValueObjects.TicketTypeSnapshot", "Tickets", b1 =>
                        {
                            b1.Property<Guid>("RegistrationId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasJsonPropertyName("name");

                            b1.Property<string>("Slug")
                                .IsRequired()
                                .HasJsonPropertyName("slug");

                            b1.PrimitiveCollection<string>("TimeSlots")
                                .IsRequired()
                                .HasJsonPropertyName("time_slots");

                            b1.HasKey("RegistrationId", "__synthesizedOrdinal");

                            b1.ToTable("registrations", "registrations");

                            b1
                                .ToJson("tickets")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationId");
                        });

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Amolenk.Admitto.Module.Registrations.Domain.Entities.TicketCatalog", b =>
                {
                    b.OwnsMany("Amolenk.Admitto.Module.Registrations.Domain.Entities.TicketType", "TicketTypes", b1 =>
                        {
                            b1.Property<Guid>("TicketCatalogId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasJsonPropertyName("slug");

                            b1.Property<bool>("IsCancelled")
                                .HasJsonPropertyName("is_cancelled");

                            b1.Property<int?>("MaxCapacity")
                                .HasJsonPropertyName("max_capacity");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasJsonPropertyName("name");

                            b1.PrimitiveCollection<string>("TimeSlotSlugs")
                                .IsRequired()
                                .HasJsonPropertyName("time_slots");

                            b1.Property<int>("UsedCapacity")
                                .HasJsonPropertyName("used_capacity");

                            b1.HasKey("TicketCatalogId", "__synthesizedOrdinal");

                            b1.ToTable("ticket_catalog", "registrations");

                            b1
                                .ToJson("ticket_types")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TicketCatalogId");
                        });

                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("Amolenk.Admitto.Module.Registrations.Domain.Entities.TicketedEvent", b =>
                {
                    b.OwnsOne("Amolenk.Admitto.Module.Registrations.Domain.ValueObjects.TicketedEventCancellationPolicy", "CancellationPolicy", b1 =>
                        {
                            b1.Property<Guid>("TicketedEventId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("LateCancellationCutoff")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("cancellation_policy_late_cutoff");

                            b1.HasKey("TicketedEventId");

                            b1.ToTable("ticketed_events", "registrations");

                            b1.WithOwner()
                                .HasForeignKey("TicketedEventId");
                        });

                    b.OwnsOne("Amolenk.Admitto.Module.Registrations.Domain.ValueObjects.TicketedEventReconfirmPolicy", "ReconfirmPolicy", b1 =>
                        {
                            b1.Property<Guid>("TicketedEventId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("Cadence")
                                .HasColumnType("interval")
                                .HasColumnName("reconfirm_policy_cadence");

                            b1.Property<DateTimeOffset>("ClosesAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("reconfirm_policy_closes_at");

                            b1.Property<DateTimeOffset>("OpensAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("reconfirm_policy_opens_at");

                            b1.HasKey("TicketedEventId");

                            b1.ToTable("ticketed_events", "registrations");

                            b1.WithOwner()
                                .HasForeignKey("TicketedEventId");
                        });

                    b.OwnsOne("Amolenk.Admitto.Module.Registrations.Domain.ValueObjects.TicketedEventRegistrationPolicy", "RegistrationPolicy", b1 =>
                        {
                            b1.Property<Guid>("TicketedEventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AllowedEmailDomain")
                                .HasMaxLength(253)
                                .HasColumnType("character varying(253)")
                                .HasColumnName("registration_policy_allowed_email_domain");

                            b1.Property<DateTimeOffset>("ClosesAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("registration_policy_closes_at");

                            b1.Property<DateTimeOffset>("OpensAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("registration_policy_opens_at");

                            b1.HasKey("TicketedEventId");

                            b1.ToTable("ticketed_events", "registrations");

                            b1.WithOwner()
                                .HasForeignKey("TicketedEventId");
                        });

                    b.Navigation("CancellationPolicy");

                    b.Navigation("ReconfirmPolicy");

                    b.Navigation("RegistrationPolicy");
                });
#pragma warning restore 612, 618
        }
    }
}
