// <auto-generated/>
#pragma warning disable CS0618
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Bulk.Custom;
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Bulk.Reconfirm;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Bulk
{
    /// <summary>
    /// Builds and executes requests for operations under \teams\{teamSlug}\events\{eventSlug}\emails\bulk
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BulkRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The custom property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Bulk.Custom.CustomRequestBuilder Custom
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Bulk.Custom.CustomRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reconfirm property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Bulk.Reconfirm.ReconfirmRequestBuilder Reconfirm
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Bulk.Reconfirm.ReconfirmRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Bulk.BulkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BulkRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/teams/{teamSlug}/events/{eventSlug}/emails/bulk", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Bulk.BulkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BulkRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/teams/{teamSlug}/events/{eventSlug}/emails/bulk", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
