// <auto-generated/>
#pragma warning disable CS0618
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Item.Preview;
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Item.Test;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \teams\{teamSlug}\events\{eventSlug}\emails\{emailType}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithEmailTypeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The preview property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Item.Preview.PreviewRequestBuilder Preview
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Item.Preview.PreviewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The test property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Item.Test.TestRequestBuilder Test
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Item.Test.TestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Item.WithEmailTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEmailTypeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/teams/{teamSlug}/events/{eventSlug}/emails/{emailType}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Item.WithEmailTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEmailTypeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/teams/{teamSlug}/events/{eventSlug}/emails/{emailType}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
