// <auto-generated/>
#pragma warning disable CS0618
using Amolenk.Admitto.Cli.Api.QrCodes.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Amolenk.Admitto.Cli.Api.QrCodes
{
    /// <summary>
    /// Builds and executes requests for operations under \qr-codes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QrCodesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Amolenk.Admitto.Cli.Api.qrCodes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Amolenk.Admitto.Cli.Api.QrCodes.Item.WithQrCodeItemRequestBuilder"/></returns>
        public global::Amolenk.Admitto.Cli.Api.QrCodes.Item.WithQrCodeItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("qrCodeId", position);
                return new global::Amolenk.Admitto.Cli.Api.QrCodes.Item.WithQrCodeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Amolenk.Admitto.Cli.Api.qrCodes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Amolenk.Admitto.Cli.Api.QrCodes.Item.WithQrCodeItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Amolenk.Admitto.Cli.Api.QrCodes.Item.WithQrCodeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("qrCodeId", position);
                return new global::Amolenk.Admitto.Cli.Api.QrCodes.Item.WithQrCodeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.QrCodes.QrCodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QrCodesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/qr-codes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.QrCodes.QrCodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QrCodesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/qr-codes", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
