// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Amolenk.Admitto.Cli.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AttendeeStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unverified")]
        #pragma warning disable CS1591
        Unverified,
        #pragma warning restore CS1591
        [EnumMember(Value = "verified")]
        #pragma warning disable CS1591
        Verified,
        #pragma warning restore CS1591
        [EnumMember(Value = "verificationFailed")]
        #pragma warning disable CS1591
        VerificationFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "registered")]
        #pragma warning disable CS1591
        Registered,
        #pragma warning restore CS1591
        [EnumMember(Value = "rejected")]
        #pragma warning disable CS1591
        Rejected,
        #pragma warning restore CS1591
        [EnumMember(Value = "reconfirmed")]
        #pragma warning disable CS1591
        Reconfirmed,
        #pragma warning restore CS1591
        [EnumMember(Value = "attendedEvent")]
        #pragma warning disable CS1591
        AttendedEvent,
        #pragma warning restore CS1591
        [EnumMember(Value = "canceledOnTime")]
        #pragma warning disable CS1591
        CanceledOnTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "canceledLastMinute")]
        #pragma warning disable CS1591
        CanceledLastMinute,
        #pragma warning restore CS1591
        [EnumMember(Value = "skippedEvent")]
        #pragma warning disable CS1591
        SkippedEvent,
        #pragma warning restore CS1591
    }
}
