// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Amolenk.Admitto.Cli.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BulkEmailWorkItemDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The emailType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailType { get; set; }
#nullable restore
#else
        public string EmailType { get; set; }
#endif
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The lastRunAt property</summary>
        public DateTimeOffset? LastRunAt { get; set; }
        /// <summary>The repeat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Amolenk.Admitto.Cli.Api.Models.BulkEmailWorkItemRepeatDto? Repeat { get; set; }
#nullable restore
#else
        public global::Amolenk.Admitto.Cli.Api.Models.BulkEmailWorkItemRepeatDto Repeat { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Amolenk.Admitto.Cli.Api.Models.BulkEmailWorkItemStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Models.BulkEmailWorkItemDto"/> and sets the default values.
        /// </summary>
        public BulkEmailWorkItemDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Amolenk.Admitto.Cli.Api.Models.BulkEmailWorkItemDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Amolenk.Admitto.Cli.Api.Models.BulkEmailWorkItemDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Amolenk.Admitto.Cli.Api.Models.BulkEmailWorkItemDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "emailType", n => { EmailType = n.GetStringValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "lastRunAt", n => { LastRunAt = n.GetDateTimeOffsetValue(); } },
                { "repeat", n => { Repeat = n.GetObjectValue<global::Amolenk.Admitto.Cli.Api.Models.BulkEmailWorkItemRepeatDto>(global::Amolenk.Admitto.Cli.Api.Models.BulkEmailWorkItemRepeatDto.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Amolenk.Admitto.Cli.Api.Models.BulkEmailWorkItemStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("emailType", EmailType);
            writer.WriteStringValue("error", Error);
            writer.WriteGuidValue("id", Id);
            writer.WriteDateTimeOffsetValue("lastRunAt", LastRunAt);
            writer.WriteObjectValue<global::Amolenk.Admitto.Cli.Api.Models.BulkEmailWorkItemRepeatDto>("repeat", Repeat);
            writer.WriteEnumValue<global::Amolenk.Admitto.Cli.Api.Models.BulkEmailWorkItemStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
