// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Amolenk.Admitto.Cli.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CheckInResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attendeeStatus property</summary>
        public global::Amolenk.Admitto.Cli.Api.Models.NullableOfParticipationAttendeeStatus? AttendeeStatus { get; set; }
        /// <summary>The contributorStatus property</summary>
        public global::Amolenk.Admitto.Cli.Api.Models.NullableOfParticipationContributorStatus? ContributorStatus { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The lastModifiedAt property</summary>
        public DateTimeOffset? LastModifiedAt { get; set; }
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Models.CheckInResponse"/> and sets the default values.
        /// </summary>
        public CheckInResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Amolenk.Admitto.Cli.Api.Models.CheckInResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Amolenk.Admitto.Cli.Api.Models.CheckInResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Amolenk.Admitto.Cli.Api.Models.CheckInResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attendeeStatus", n => { AttendeeStatus = n.GetEnumValue<global::Amolenk.Admitto.Cli.Api.Models.NullableOfParticipationAttendeeStatus>(); } },
                { "contributorStatus", n => { ContributorStatus = n.GetEnumValue<global::Amolenk.Admitto.Cli.Api.Models.NullableOfParticipationContributorStatus>(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "lastModifiedAt", n => { LastModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Amolenk.Admitto.Cli.Api.Models.NullableOfParticipationAttendeeStatus>("attendeeStatus", AttendeeStatus);
            writer.WriteEnumValue<global::Amolenk.Admitto.Cli.Api.Models.NullableOfParticipationContributorStatus>("contributorStatus", ContributorStatus);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteDateTimeOffsetValue("lastModifiedAt", LastModifiedAt);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
