// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Amolenk.Admitto.Cli.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetAttendeeResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The activities property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Amolenk.Admitto.Cli.Api.Models.ActivityDto>? Activities { get; set; }
#nullable restore
#else
        public List<global::Amolenk.Admitto.Cli.Api.Models.ActivityDto> Activities { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The additionalDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Amolenk.Admitto.Cli.Api.Models.AdditionalDetailDto>? AdditionalDetails { get; set; }
#nullable restore
#else
        public List<global::Amolenk.Admitto.Cli.Api.Models.AdditionalDetailDto> AdditionalDetails { get; set; }
#endif
        /// <summary>The attendeeId property</summary>
        public Guid? AttendeeId { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The lastChangedAt property</summary>
        public DateTimeOffset? LastChangedAt { get; set; }
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The registrationStatus property</summary>
        public global::Amolenk.Admitto.Cli.Api.Models.RegistrationStatus? RegistrationStatus { get; set; }
        /// <summary>The tickets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Amolenk.Admitto.Cli.Api.Models.TicketSelectionDto>? Tickets { get; set; }
#nullable restore
#else
        public List<global::Amolenk.Admitto.Cli.Api.Models.TicketSelectionDto> Tickets { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Models.GetAttendeeResponse"/> and sets the default values.
        /// </summary>
        public GetAttendeeResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Amolenk.Admitto.Cli.Api.Models.GetAttendeeResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Amolenk.Admitto.Cli.Api.Models.GetAttendeeResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Amolenk.Admitto.Cli.Api.Models.GetAttendeeResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activities", n => { Activities = n.GetCollectionOfObjectValues<global::Amolenk.Admitto.Cli.Api.Models.ActivityDto>(global::Amolenk.Admitto.Cli.Api.Models.ActivityDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "additionalDetails", n => { AdditionalDetails = n.GetCollectionOfObjectValues<global::Amolenk.Admitto.Cli.Api.Models.AdditionalDetailDto>(global::Amolenk.Admitto.Cli.Api.Models.AdditionalDetailDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "attendeeId", n => { AttendeeId = n.GetGuidValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "lastChangedAt", n => { LastChangedAt = n.GetDateTimeOffsetValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "registrationStatus", n => { RegistrationStatus = n.GetEnumValue<global::Amolenk.Admitto.Cli.Api.Models.RegistrationStatus>(); } },
                { "tickets", n => { Tickets = n.GetCollectionOfObjectValues<global::Amolenk.Admitto.Cli.Api.Models.TicketSelectionDto>(global::Amolenk.Admitto.Cli.Api.Models.TicketSelectionDto.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Amolenk.Admitto.Cli.Api.Models.ActivityDto>("activities", Activities);
            writer.WriteCollectionOfObjectValues<global::Amolenk.Admitto.Cli.Api.Models.AdditionalDetailDto>("additionalDetails", AdditionalDetails);
            writer.WriteGuidValue("attendeeId", AttendeeId);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteDateTimeOffsetValue("lastChangedAt", LastChangedAt);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteEnumValue<global::Amolenk.Admitto.Cli.Api.Models.RegistrationStatus>("registrationStatus", RegistrationStatus);
            writer.WriteCollectionOfObjectValues<global::Amolenk.Admitto.Cli.Api.Models.TicketSelectionDto>("tickets", Tickets);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
