// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Amolenk.Admitto.Cli.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetTicketedEventResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The baseUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseUrl { get; set; }
#nullable restore
#else
        public string BaseUrl { get; set; }
#endif
        /// <summary>The endDateTime property</summary>
        public DateTimeOffset? EndDateTime { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The registrationEndDateTime property</summary>
        public DateTimeOffset? RegistrationEndDateTime { get; set; }
        /// <summary>The registrationStartDateTime property</summary>
        public DateTimeOffset? RegistrationStartDateTime { get; set; }
        /// <summary>The slug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>The startDateTime property</summary>
        public DateTimeOffset? StartDateTime { get; set; }
        /// <summary>The ticketTypes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Amolenk.Admitto.Cli.Api.Models.TicketTypeDto>? TicketTypes { get; set; }
#nullable restore
#else
        public List<global::Amolenk.Admitto.Cli.Api.Models.TicketTypeDto> TicketTypes { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Models.GetTicketedEventResponse"/> and sets the default values.
        /// </summary>
        public GetTicketedEventResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Amolenk.Admitto.Cli.Api.Models.GetTicketedEventResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Amolenk.Admitto.Cli.Api.Models.GetTicketedEventResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Amolenk.Admitto.Cli.Api.Models.GetTicketedEventResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "baseUrl", n => { BaseUrl = n.GetStringValue(); } },
                { "endDateTime", n => { EndDateTime = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "registrationEndDateTime", n => { RegistrationEndDateTime = n.GetDateTimeOffsetValue(); } },
                { "registrationStartDateTime", n => { RegistrationStartDateTime = n.GetDateTimeOffsetValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "startDateTime", n => { StartDateTime = n.GetDateTimeOffsetValue(); } },
                { "ticketTypes", n => { TicketTypes = n.GetCollectionOfObjectValues<global::Amolenk.Admitto.Cli.Api.Models.TicketTypeDto>(global::Amolenk.Admitto.Cli.Api.Models.TicketTypeDto.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("baseUrl", BaseUrl);
            writer.WriteDateTimeOffsetValue("endDateTime", EndDateTime);
            writer.WriteStringValue("name", Name);
            writer.WriteDateTimeOffsetValue("registrationEndDateTime", RegistrationEndDateTime);
            writer.WriteDateTimeOffsetValue("registrationStartDateTime", RegistrationStartDateTime);
            writer.WriteStringValue("slug", Slug);
            writer.WriteDateTimeOffsetValue("startDateTime", StartDateTime);
            writer.WriteCollectionOfObjectValues<global::Amolenk.Admitto.Cli.Api.Models.TicketTypeDto>("ticketTypes", TicketTypes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
