// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Amolenk.Admitto.Cli.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ParticipationAttendeeStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "registered")]
        #pragma warning disable CS1591
        Registered,
        #pragma warning restore CS1591
        [EnumMember(Value = "canceled")]
        #pragma warning disable CS1591
        Canceled,
        #pragma warning restore CS1591
    }
}
