// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Amolenk.Admitto.Cli.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TeamMemberRole
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "manager")]
        #pragma warning disable CS1591
        Manager,
        #pragma warning restore CS1591
        [EnumMember(Value = "organizer")]
        #pragma warning disable CS1591
        Organizer,
        #pragma warning restore CS1591
    }
}
