apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  initTimeout: 5m
  metadata:
    - name: keyPrefix
      value: none
    - name: url
      value: https://localhost:8081
    - name: masterKey
      value: "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
    - name: database
      value: admitto
    - name: collection
      value: core
    - name: outboxPublishPubsub
      value: "pubsub"
    - name: outboxPublishTopic
      value: "orders"
