// <auto-generated/>
#pragma warning disable CS0618
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Bulk;
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Item;
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Reconfirm;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails
{
    /// <summary>
    /// Builds and executes requests for operations under \teams\{teamSlug}\events\{eventSlug}\emails
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EmailsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bulk property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Bulk.BulkRequestBuilder Bulk
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Bulk.BulkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reconfirm property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Reconfirm.ReconfirmRequestBuilder Reconfirm
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Reconfirm.ReconfirmRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Amolenk.Admitto.Cli.Api.teams.item.events.item.emails.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Item.WithEmailTypeItemRequestBuilder"/></returns>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Item.WithEmailTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("emailType", position);
                return new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.Item.WithEmailTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.EmailsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmailsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/teams/{teamSlug}/events/{eventSlug}/emails", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.EmailsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmailsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/teams/{teamSlug}/events/{eventSlug}/emails", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
