// <auto-generated/>
#pragma warning disable CS0618
using Amolenk.Admitto.Cli.Api.Models;
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Attendees;
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Contributors;
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailRecipientLists;
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailTemplates;
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails;
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Policies;
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Public;
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.TicketTypes;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \teams\{teamSlug}\events\{eventSlug}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithEventSlugItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The attendees property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Attendees.AttendeesRequestBuilder Attendees
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Attendees.AttendeesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contributors property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Contributors.ContributorsRequestBuilder Contributors
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Contributors.ContributorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emailRecipientLists property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailRecipientLists.EmailRecipientListsRequestBuilder EmailRecipientLists
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailRecipientLists.EmailRecipientListsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emails property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.EmailsRequestBuilder Emails
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Emails.EmailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emailTemplates property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailTemplates.EmailTemplatesRequestBuilder EmailTemplates
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailTemplates.EmailTemplatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The policies property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Policies.PoliciesRequestBuilder Policies
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Policies.PoliciesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The public property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Public.PublicRequestBuilder Public
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.Public.PublicRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ticketTypes property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.TicketTypes.TicketTypesRequestBuilder TicketTypes
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.TicketTypes.TicketTypesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.WithEventSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEventSlugItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/teams/{teamSlug}/events/{eventSlug}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.WithEventSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEventSlugItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/teams/{teamSlug}/events/{eventSlug}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Amolenk.Admitto.Cli.Api.Models.GetTicketedEventResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Amolenk.Admitto.Cli.Api.Models.HttpValidationProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails">When receiving a 403 status code</exception>
        /// <exception cref="global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails">When receiving a 409 status code</exception>
        /// <exception cref="global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Amolenk.Admitto.Cli.Api.Models.GetTicketedEventResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Amolenk.Admitto.Cli.Api.Models.GetTicketedEventResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Amolenk.Admitto.Cli.Api.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "403", global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "409", global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Amolenk.Admitto.Cli.Api.Models.GetTicketedEventResponse>(requestInfo, global::Amolenk.Admitto.Cli.Api.Models.GetTicketedEventResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Amolenk.Admitto.Cli.Api.Models.HttpValidationProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails">When receiving a 403 status code</exception>
        /// <exception cref="global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails">When receiving a 409 status code</exception>
        /// <exception cref="global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PatchAsync(global::Amolenk.Admitto.Cli.Api.Models.UpdateTicketedEventRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PatchAsync(global::Amolenk.Admitto.Cli.Api.Models.UpdateTicketedEventRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Amolenk.Admitto.Cli.Api.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "403", global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "409", global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::Amolenk.Admitto.Cli.Api.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Amolenk.Admitto.Cli.Api.Models.UpdateTicketedEventRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Amolenk.Admitto.Cli.Api.Models.UpdateTicketedEventRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/problem+json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.WithEventSlugItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.WithEventSlugItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.WithEventSlugItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithEventSlugItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithEventSlugItemRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
