// <auto-generated/>
#pragma warning disable CS0618
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailVerification.Requests;
using Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailVerification.Verify;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailVerification
{
    /// <summary>
    /// Builds and executes requests for operations under \teams\{teamSlug}\events\{eventSlug}\email-verification
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EmailVerificationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The requests property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailVerification.Requests.RequestsRequestBuilder Requests
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailVerification.Requests.RequestsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The verify property</summary>
        public global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailVerification.Verify.VerifyRequestBuilder Verify
        {
            get => new global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailVerification.Verify.VerifyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailVerification.EmailVerificationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmailVerificationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/teams/{teamSlug}/events/{eventSlug}/email-verification", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amolenk.Admitto.Cli.Api.Teams.Item.Events.Item.EmailVerification.EmailVerificationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmailVerificationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/teams/{teamSlug}/events/{eventSlug}/email-verification", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
