name: Build Admitto CLI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/Admitto.Cli/**'
  workflow_dispatch: {}

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build CLI
      run: |
        dotnet build src/Admitto.Cli/Admitto.Cli.csproj -c Release
