name: Provision Infrastructure

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/provision.yml'

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            
            
            
          
#      - name: Deploy Bicep
#        run: |
#          az deployment sub create \
#            --location westeurope \
#            --template-file infra/main.bicep \
#            --parameters environment=prod