<Project Sdk="Aspire.AppHost.Sdk/13.4.4">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Admitto.Api\Admitto.Api.csproj" />
        <ProjectReference Include="..\Admitto.Core\Admitto.Core.csproj" IsAspireProjectResource="false" />
        <ProjectReference Include="..\Admitto.Worker\Admitto.Worker.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.Azure.AppContainers" />
        <PackageReference Include="Aspire.Hosting.Azure.ApplicationInsights" />
        <PackageReference Include="Aspire.Hosting.EntityFrameworkCore" />
        <PackageReference Include="Aspire.Hosting.Azure.OperationalInsights" />
        <PackageReference Include="Aspire.Hosting.Azure.PostgreSQL" />
        <PackageReference Include="Aspire.Hosting.Azure.ServiceBus" />
        <PackageReference Include="Aspire.Hosting.PostgreSQL" />
        <PackageReference Include="Azure.Identity" />
        <PackageReference Include="Aspire.Hosting.JavaScript" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="DatabaseScripts\*.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
    </ItemGroup>


<!--    TODO  Install npm pacakges if missing -->
<!--    <Target Name="RestoreNpm" BeforeTargets="Build" Condition=" '$(DesignTimeBuild)' != 'true' ">-->
<!--        <ItemGroup>-->
<!--            <PackageJsons Include="..\*\package.json" />-->
<!--        </ItemGroup>-->

<!--        &lt;!&ndash; Install npm packages if node_modules is missing &ndash;&gt;-->
<!--        <Message Importance="Normal" Text="Installing npm packages for %(PackageJsons.RelativeDir)" Condition="!Exists('%(PackageJsons.RootDir)%(PackageJsons.Directory)/node_modules')" />-->
<!--        <Exec Command="npm install" WorkingDirectory="%(PackageJsons.RootDir)%(PackageJsons.Directory)" Condition="!Exists('%(PackageJsons.RootDir)%(PackageJsons.Directory)/node_modules')" />-->
<!--    </Target>-->
    
</Project>
